repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-ast
          - id: debug-statements
          - id: check-yaml
          - id: check-toml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
          - id: isort
    - repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
          - id: black
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.10.0
      hooks:
          - id: python-no-eval
    - repo: https://github.com/twu/skjold
      rev: v0.6.1
      hooks:
          - id: skjold
