ENABLE_RESOURCE_RETRIVE = 1
ENABLE_RESOURCE_LIST = 2
ENABLE_RESOURCE_READ = ENABLE_RESOURCE_RETRIVE | ENABLE_RESOURCE_LIST
ENABLE_RESOURCE_CREATE = 4
ENABLE_RESOURCE_UPDATE = 8
ENABLE_RESOURCE_PARTIAL_UPDATE = 16
ENABLE_RESOURCE_DESTROY = 32
ENABLE_RESOURCE_ALL = (
    ENABLE_RESOURCE_RETRIVE
    | ENABLE_RESOURCE_LIST
    | ENABLE_RESOURCE_CREATE
    | ENABLE_RESOURCE_UPDATE
    | ENABLE_RESOURCE_PARTIAL_UPDATE
    | ENABLE_RESOURCE_DESTROY
)
