"""initial database

Revision ID: e9548fb98646
Revises:
Create Date: 2023-02-19 23:27:08.866714

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e9548fb98646"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "owner",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("phone_number", sa.String(length=12), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pet_type",
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pet",
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("pet_type_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("sex", sa.String(length=1), nullable=False),
        sa.Column("born_date", sa.Date(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["owner.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pet_type_id"],
            ["pet_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pet")
    op.drop_table("pet_type")
    op.drop_table("owner")
    # ### end Alembic commands ###
